<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a 
                    class="nav-header" 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                        <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                    <?php
                                    continue;
                                endif;
                                ?>
                            <?php $appendClass = ''?>
                            <?php if($child->getPages()):?>
                            <?php foreach($child->getPages() as $lv2Child):?>
                                <?php if($lv2Child->isActive()): ?>
                                <?php $appendClass= "class='active open'"; break;?>
                                <?php endif;?>
                            <?php endforeach;?>
                            <?php endif;?>
                            
                            <li <?= $child->isActive()? "class='active'" : $appendClass?>>

                                <a 
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?> >
                                        <?php if ($child->get("icon") !== ""): ?>
                                        <i class="<?php echo $child->get("icon"); ?>"></i>
                                    <?php endif; ?>
                                    <span class="title">
                                    <?php echo $this->escapeHtml($this->translate($child->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
                                    </span>
                                    <span<?php if ($child->isActive()) echo ' class="selected"' ?>></span>
                                    <span class="arrow <?php if ($appendClass) echo 'open' ?>"></span>
                                </a>
                                <?php if($child->getPages()):?>
                                <ul class="sub-menu">
                                    <?php foreach($child->getPages() as $lv2Child):?>
                                    
                                    <?php $appendClass3 = ''?>
                                    <?php if($lv2Child->getPages()):?>
                                    <?php foreach($lv2Child->getPages() as $lv3Child):?>
                                        <?php if($lv3Child->isActive()): ?>
                                        <?php $appendClass3 = "class='active open'"; break;?>
                                        <?php endif;?>
                                    <?php endforeach;?>
                                    <?php endif;?>
                                    
            						<li <?= $appendClass3 ?>>
            							<a href="<?php echo $lv2Child->getHref() ?>">
            							<?php echo $this->escapeHtml($this->translate($lv2Child->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
            							</a>
            						</li>
            						<?php endforeach;?>
            					</ul>
                                <?php endif;?>
                            </li>
                        <?php endforeach ?>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>