<div class="portlet light">
    <div class="portlet-title">
		<div class="caption">
			<i class="fa fa-users"></i>All Projects
		</div>

		<div class="pull-right">
				<a href="<?= $this->url('project/add')?>" class="btn btn-success yellow-stripe"> <i
					class="fa fa-plus"></i> <span class="hidden-480"> New Project </span>
				</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-container">
			<table class="table table-striped table-bordered table-hover"
				id="project-listing">
				<thead>
					<tr role="row" class="heading">
						<th class="col-checkbox" width="2%"><input type="checkbox"
							class="group-checkable"></th>
						<th>Project Id</th>
						<th>Name</th>
						<th class="col-project-listing-action">Actions</th>
					</tr>
					<tr role="row" class="filter">
										<td>
										</td>
										<td>
											<input type="text" class="form-control form-filter input-sm" name="filter[id_is]">
										</td>
										<td>
											<input type="text" class="form-control form-filter input-sm" name="filter[name_contains]">
										</td>
										<td>
											<div class="margin-bottom-5">
												<button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
											</div>
											<button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
										</td>
									</tr>
				<thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>
<?php
$ajaxUrl = $this->url('project');
$updateProjecttUrl = $this->url('project/update', array('projectId' => '__entityId__'));

$this->inlineScript()->captureStart();
echo <<<JS
jQuery(document).ready(function() {
	var settings = {url: "$ajaxUrl", table: "#project-listing"};
	grid = TableAjax.init(settings);
		    
	$('#project-listing').on( 'click', 'tbody tr', function () {
	  var goTo = "$updateProjecttUrl".replace('__entityId__', $(this).attr('id'));
      window.location.href = goTo;
    } );
});
JS;
$this->inlineScript()->captureEnd();
?>