<?php $this->headLink()->appendStylesheet('/assets/global/plugins/fullcalendar/fullcalendar.min.css'); ?>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered calendar">
            <div class="portlet-title">
                <div class="caption">
                    <i class=" icon-layers font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">Calendar</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <!-- BEGIN DRAGGABLE EVENTS PORTLET-->
                        <h3 class="event-form-title margin-bottom-20">Draggable Events</h3>
                        <div id="external-events">
                            <form class="inline-form">
                                <input type="text" value="" class="form-control" placeholder="Event Title..." id="event_title" />
                                <br/>
                                <a href="javascript:;" id="event_add" class="btn green"> Add Event </a>
                            </form>
                            <hr/>
                            <div id="event_box" class="margin-bottom-10"></div>
                            <label for="drop-remove">
                                <input type="checkbox" id="drop-remove" />remove after drop </label>
                            <hr class="visible-xs" /> </div>
                        <!-- END DRAGGABLE EVENTS PORTLET-->
                        <div id="rubbish-bin" class="thumbnail" style="height: 180px; width: 100%; display: block;"><i class="fa fa-trash"></i> Drop events here to remove</div>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div id="calendar" class="has-toolbar"> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
$this->inlineScript()->appendFile($this->basePath('/assets/global/plugins/moment.min.js'));
$this->inlineScript()->appendFile($this->basePath('/assets/global/plugins/fullcalendar/fullcalendar.min.js'));
$this->inlineScript()->appendFile($this->basePath('/assets/global/plugins/jquery-ui/jquery-ui.min.js'));
$this->inlineScript()->appendFile($this->basePath('/customAssets/calendar.js'));
// $this->inlineScript()->captureStart();
// echo <<<JS
// jQuery(document).ready(function() {

//     $('#calendar').fullCalendar({
// 		    googleCalendarApiKey: 'AIzaSyC4adbvM_SZpO18Azmuvg7kKZiJhiXod8o',
// // 		    events: {
// //                 googleCalendarId: 'ub52bmjskn0tgtd4vspnugfcuk@group.calendar.google.com'
// //             },
// 		    events: [
// 			{
// 				title: 'All Day Event',
// 				start: '2015-02-01'
// 			},
// 			{
// 				title: 'Long Event',
// 				start: '2015-02-07',
// 				end: '2015-02-10'
// 			},
// 			{
// 				id: 999,
// 				title: 'Repeating Event',
// 				start: '2015-02-09T16:00:00'
// 			},
// 			{
// 				id: 999,
// 				title: 'Repeating Event',
// 				start: '2015-02-16T16:00:00'
// 			},
// 			{
// 				title: 'Conference',
// 				start: '2015-02-11',
// 				end: '2015-02-13'
// 			},
// 			{
// 				title: 'Meeting',
// 				start: '2015-11-30T10:30:00',
// 				end: '2015-11-30T12:30:00'
// 			},
// 			{
// 				title: 'Lunch',
// 				start: '2015-11-30T12:00:00'
// 			},
// 			{
// 				title: 'Meeting',
// 				start: '2015-11-30T14:30:00'
// 			},
// 			{
// 				title: 'Happy Hour',
// 				start: '2015-11-30T17:30:00'
// 			},
// 			{
// 				title: 'Dinner',
// 				start: '2015-11-30T20:00:00'
// 			},
// 			{
// 				title: 'Birthday Party',
// 				start: '2015-11-30T07:00:00',
// 		        siwei: 'haha'
// 			},
// 			{
// 				title: 'Click for Google',
// 				url: 'http://google.com/',
// 				start: '2015-11-30'
// 			}
// 		],
// 		    header: {
//                left: 'prev,next today',
//                center: 'title',
//                right: 'month,agendaWeek,agendaDay'
//             },
//             editable: true,
//             droppable: true,
//             dayClick: function(date, jsEvent, view) {
    
//                 //alert('Clicked on: ' + date.format());
        
//                 //alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
        
//                 //alert('Current view: ' + view.name);
        
//                 // change the day's background color just for fun
//                 $(this).css('background-color', 'red');
//             },
// 		    eventClick: function(event) {
//                 if (event.siwei) {
//                     console.log(event.siwei);
//                     return false;
//                 }
//             },
// 		    eventReceive: function(event){
//                var title = event.title;
//                var start = event.start.format("YYYY-MM-DD[T]HH:MM:SS");
// //                $.ajax({
// //                  url: 'process.php',
// //                  data: 'type=new&title='+title+'&startdate='+start+'&zone='+zone,
// //                  type: 'POST',
// //                  dataType: 'json',
// //                  success: function(response){
// //                    event.id = response.eventid;
// //                    $('#calendar').fullCalendar('updateEvent',event);
// //                  },
// //                  error: function(e){
// //                    console.log(e.responseText);
// //                  }
// //                });
//                $('#calendar').fullCalendar('updateEvent',event);
//             },
// 		    eventDrop: function(event, delta, revertFunc) {
//                var title = event.title;
//                var start = event.start.format();
//                var end = (event.end == null) ? start : event.end.format();
// //                u$.ajax({
// //                  url: 'process.php',
// //                  data: 'type=resetdate&title='+title+'&start='+start+'&end='+end+'&eventid='+id,
// //                  type: 'POST',
// //                  dataType: 'json',
// //                  success: function(response){
// //                    if(response.status != 'success')
// //                    revertFunc();
// //                  },
// //                  error: function(e){
// //                    revertFunc();
// //                    alert('Error processing your request: '+e.responseText);
// //                  }
// //                  });
//             }
//     })
// });
// JS;
// $this->inlineScript()->captureEnd();
?>