<?php if ($this->source->has($this->name)): ?>
    <?php $element = $this->source->get($this->name); ?>
    <?php if($this->hasLabel === false): ?>
        <?php if(isset($this->widthClass)): ?>
        <div class="<?= $this->widthClass ?>">
    		<?= $this->formInput($element)?>
    		<span class="help-block"><?= $this->formElementErrors($element); ?></span>
    		</div>
        <?php else:?>
        <div class="form-group">
        		<?= $this->formInput($this->source) ?>
        		<span class="help-block"><?= $this->formElementErrors($element); ?></span>
        </div>
        <?php endif;?>
    <?php else: ?>
    <div class="form-group">
        <?php if($this->isVertical): ?>
            <label><?= $this->formLabel($element) ?></label>
    		<?= $this->formInput($element)?>
    		<span class="help-block"><?= $this->formElementErrors($element); ?></span>
        <?php else:?>
    	<div class="row">
    		<label class="col-md-3 control-label"><?= $this->formLabel($element) ?></label>
    		<div class="col-md-9">
    		<?= $this->formInput($element)?>
    		<span class="help-block"><?= $this->formElementErrors($element); ?></span>
    		</div>
    	</div>
    	<?php endif;?>
    </div>
    <?php endif; ?>
<?php endif; ?>