<?php if ($this->source->has($this->name)): ?>
    <?php $element = $this->source->get($this->name); ?>
    <?php 
    $options = $element->getOptions(); 
    $description = '';
    if( isset($options['description']) )
        $description = $options['description']
    ?>
    <?php $helpBlock = '<span class="help-block">' . $description . $this->formElementErrors($element); '</span>;' ?>
    <?php if($this->hasLabel === false): ?>
    <div class="form-group">
    		<?= $this->formInput($element) ?>
    		<?= $helpBlock ?>
    </div>
    <?php else: ?>
    <div class="form-group">
        <?php if($this->isVertical): ?>
            <label><?= $this->formLabel($element) ?></label>
    		<?= $this->formCheckbox($element)?>
    		<?= $helpBlock ?>
        <?php else:?>
    	<div class="row">
    		<label class="col-md-3 control-label"><?= $this->formLabel($element) ?></label>
    		<div class="col-md-9">
    		<div class="checkbox-list">
    			<label class="checkbox-inline">
    			<?= $this->formCheckbox($element) ?>
    			<?= $helpBlock ?>
    			</label>
			</div>
    		</div>
    	</div>
    	<?php endif; ?>
    </div>
    <?php endif; ?>
<?php endif;?>