<?php if ($this->source->has($this->name)): ?>
    <?php $element = $this->source->get($this->name); ?>
    <div class="form-group">
    	<div class="row">
    		<label class="control-label col-md-3"><?= $this->formLabel($element) ?></label>
    		<div class="col-md-9">
    			<div class="fileinput fileinput-new" data-provides="fileinput">
    				<div>
    					<span class="btn default btn-file"> <span class="fileinput-new">
    							Select image </span> <span class="fileinput-exists"> Change </span>
        										<input type="file" name="file">
        									</span> <a href="javascript:;"
    						class="btn red fileinput-exists" data-dismiss="fileinput"> Remove
    					</a>
    				</div>
    				<div class="fileinput-new thumbnail"
    					style="width: 300px; height: 100px;">
    					<img
    						src="http://www.placehold.it/300x100/EFEFEF/AAAAAA&amp;text=no+image"
    						alt="" />
    				</div>
    				<div class="fileinput-preview fileinput-exists thumbnail"
    					style="max-width: 300px; max-height: 100px;"></div>
    			</div>
    			<span class="help-block"><?= $this->formElementErrors($element); ?></span>
    		</div>
    	</div>
    </div>
<?php endif; ?>