<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate("iNerds Dashboard"))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Core Styles -->
        <?php echo $this->render('layout/css') ?>
        <?php echo $this->headLink();?>

    </head>
    <body class="page-md page-header-fixed page-quick-sidebar-over-content">
        <?= $this->render('blocks/header.phtml')?>
        <!-- BEGIN CONTAINER -->
        
		<div class="page-container">
		    <!-- BEGIN SIDEBAR -->
		    <?php
		    //if ($this->isAllowed('adminNavigation', 'view')) {
		        echo $this->render('blocks/adminSidebar.phtml');
		    //}
		    ?>
		    <!-- END SIDEBAR -->
		    
			<!-- BEGIN CONTENT -->
            <?= $this->render('blocks/content.phtml')?>
			<!-- END CONTENT -->
		</div>
		<!-- END CONTAINER -->
     	<?= $this->render('blocks/footer.phtml')?>
     	<!-- Scripts -->
        <?php echo $this->render('layout/js') ?>
        
     	<?php echo $this->inlineScript() ?>

    </body>
</html>



