<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Login'))->setSeparator(' - ')->setAutoEscape(false)?>
    
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
        
        <!-- Styles -->
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="/Metronic/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="/Metronic/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="/Metronic/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/Metronic/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="/Metronic/customAssets/login.css" rel="stylesheet" type="text/css">
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME STYLES -->
        <link href="/Metronic/assets/global/css/components-md.css" id="style_components" rel="stylesheet" type="text/css">
        <link href="/Metronic/assets/global/css/plugins-md.css" rel="stylesheet" type="text/css">
        <link href="/Metronic/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css">
        <link href="/Metronic/assets/admin/layout/css/themes/darkblue.css" rel="stylesheet" type="text/css" id="style_color">
        <link href="/Metronic/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- END THEME STYLES -->
        
    </head>
    
    <body class="page-md login" cz-shortcut-listen="true">
    
    	<!-- Flash Messenger -->
        <?= $this->render('layout/partial/flash-messenger')?>
    
    	<div class="content">
            <?php echo $this->content; ?>
    	</div>
    	
        <div class="copyright">St. Vincent's Vascular Laboratory Portal. Designed by <a class="btn btn-default btn-xs" href="http://www.NewtonsIT.com.au">Newton's IT</a></div>

        <!-- Scripts -->
        <script src="/Metronic/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="/Metronic/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <script src="/Metronic/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/Metronic/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/Metronic/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="/Metronic/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="/Metronic/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="/Metronic/assets/global/scripts/metronic.js" type="text/javascript"></script>
        <script src="/Metronic/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
        <script src="/Metronic/customAssets/login.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        
        <script>
    		jQuery(document).ready(function() {     
    			Metronic.init(); // init metronic core components
    			Layout.init(); // init current layout
    			Login.init();
    		});
    	</script>
        
    	<?php echo $this->inlineScript()?>
    </body>
</html>
