
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar md-shadow-z-2-i  navbar-collapse collapse">

		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu " data-keep-expanded="false"
			data-auto-scroll="true" data-slide-speed="200">
			<li class="start "><a href="/"> <i class="icon-home"></i> <span
					class="title">Dashboard</span>
			</a></li>
			<li class="active open"><a href="javascript:;"> <i
					class="icon-rocket"></i> <span class="title">Page Layouts</span> <span
					class="arrow open"></span>
			</a>
				<ul class="sub-menu">
					<li><a href="layout_sidebar_reversed.html"> <span
							class="badge badge-warning">new</span>Right Sidebar Page
					</a></li>
					<li><a href="layout_sidebar_fixed.html"> Sidebar Fixed Page</a></li>
					<li><a href="layout_sidebar_closed.html"> Sidebar Closed Page</a></li>
					<li class="active"><a href="layout_blank_page.html"> Blank Page</a>
					</li>
					<li><a href="layout_boxed_page.html"> Boxed Page</a></li>
					<li><a href="layout_language_bar.html"> Language Switch Bar</a></li>
				</ul></li>

			<li class="last "><a href="javascript:;"> <i class="icon-pointer"></i>
					<span class="title">Maps</span> <span class="arrow "></span>
			</a>
				<ul class="sub-menu">
					<li><a href="maps_google.html"> Google Maps</a></li>
					<li><a href="maps_vector.html"> Vector Maps</a></li>
				</ul></li>
		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
</div>
<!-- END SIDEBAR --