<?php
namespace Application\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{

    public function getAllCustomers()
    {
        return $this->getAll();
    }
    
    /**
     * Fetch Orders for datatable ajax function
     *
     * @param array $options            
     * @return array $output
     */
    public function getAll( $filter = null, $columnConfig = null)
    {
        $defaultColumns = [
                [
                        'field' => 'id'
                ],
                [
                        'field' => 'displayName'
                ],
                [
                        'field' => 'email'
                ],
                [
                        'field' => 'company'
                ],
                [
                        'field' => 'mobile'
                ],
                [
                        'field' => 'telephone'
                ],
                [
                        'field' => 'fax'
                ]
        ];
        
        $columnConfig = $columnConfig? : $defaultColumns;
         return $this->setupDatatable($defaultColumns, $filter);
    }
}
