<?php 
$projectId = $this->projectId;
?>
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-users"></i>All Tasks
		</div>

		<div class="pull-right">
			<a href="<?= $this->url('project/task/add', array('projectId' => $projectId ))?>"
				class="btn btn-success yellow-stripe"> <i class="fa fa-plus"></i> <span
				class="hidden-480"> New Task </span>
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="table-container">
			<table class="table table-striped table-bordered table-hover"
				id="task-listing">
				<thead>
					<tr role="row" class="heading">
						<th class="col-checkbox" width="2%"><input type="checkbox"
							class="group-checkable"></th>
						<th>Task Id</th>
						<th>Title</th>
						<th>Start On</th>
						<th class="col-task-listing-action">Actions</th>
					</tr>
					<tr role="row" class="filter">
						<td></td>
						<td><input type="text" class="form-control form-filter input-sm"
							name="filter[id_is]"></td>
						<td><input type="text" class="form-control form-filter input-sm"
							name="filter[title_contains]"></td>
						<td>
							<div class="input-group date date-picker margin-bottom-5"
								data-date-format="dd/mm/yyyy">
								<input type="text" class="form-control form-filter input-sm"
									readonly name="filter[dateOfBirth_dateGte]" placeholder="From">
								<span class="input-group-btn">
									<button class="btn btn-sm default" type="button">
										<i class="fa fa-calendar"></i>
									</button>
								</span>
							</div>
							<div class="input-group date date-picker"
								data-date-format="dd/mm/yyyy">
								<input type="text" class="form-control form-filter input-sm"
									readonly name="filter[dateOfBirth_dateLte]" placeholder="To"> <span
									class="input-group-btn">
									<button class="btn btn-sm default" type="button">
										<i class="fa fa-calendar"></i>
									</button>
								</span>
							</div>
						</td>
						<td>
							<div class="margin-bottom-5">
								<button class="btn btn-sm yellow filter-submit margin-bottom">
									<i class="fa fa-search"></i> Search
								</button>
							</div>
							<button class="btn btn-sm red filter-cancel">
								<i class="fa fa-times"></i> Reset
							</button>
						</td>
					</tr>
				<thead>
				
				
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>
<?php
$ajaxUrl = $this->url('project/task', array('projectId' => $projectId));
$updateTasktUrl = $this->url('task/update', array('taskId' => '__taskId__'));

$this->inlineScript()->captureStart();
echo <<<JS
jQuery(document).ready(function() {
	var settings = {url: "$ajaxUrl", table: "#task-listing"};
	grid = TableAjax.init(settings);
		    
	$('#task-listing').on( 'click', 'tbody tr', function () {
	  var goTo = "$updateTasktUrl".replace('__taskId__', $(this).attr('id'));
      window.location.href = goTo;
    } );
});
JS;
$this->inlineScript()->captureEnd();
?>